# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEUJJLJXV5AmWqONEklLmAIpE6wR8Toy
"""

from pathlib import Path

file_path = Path('/content/drive/MyDrive/train-bird-audio.zip')

if file_path.exists():
    print(f"Het bestand '{file_path}' is gevonden in Google Drive.")
else:
    print(f"Het bestand '{file_path}' is NIET gevonden in Google Drive. Zorg ervoor dat het daar is geüpload.")

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import soundfile as sf
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple
import zipfile


# ----------------------------
# Data structures
# ----------------------------

@dataclass(frozen=True)
class AudioExample:
    """One audio sample with inferred class label."""
    path: Path
    label: str


# ----------------------------
# Dataset loading
# ----------------------------

class FolderDatasetLoader:
    """
    Loads audio files by scanning subdirectories.
    Each subdirectory name is treated as a class label.
    """

    def __init__(self, dataset_dir: Path, extension: str = "*.mp3") -> None:
        self.dataset_dir = dataset_dir
        self.extension = extension

    def load(self) -> List[AudioExample]:
        """Scan dataset directory and load audio paths."""
        if not self.dataset_dir.exists():
            raise FileNotFoundError("Dataset directory not found")

        examples: List[AudioExample] = []

        for class_dir in sorted(self.dataset_dir.iterdir()):
            if not class_dir.is_dir():
                continue

            label = class_dir.name
            for audio_file in class_dir.glob(self.extension):
                examples.append(AudioExample(path=audio_file, label=label))

        if not examples:
            raise RuntimeError("No audio files found in dataset")

        return examples


# ----------------------------
# Audio loading
# ----------------------------

class AudioLoader:
    """Loads audio into mono signals."""

    def __init__(self, max_seconds: float | None = None) -> None:
        self.max_seconds = max_seconds

    def load_mono(self, path: Path) -> Tuple[int, np.ndarray]:
        """Load audio file as mono float64 signal."""
        data, sr = sf.read(str(path), dtype="float64", always_2d=True)
        mono = data.mean(axis=1)

        if self.max_seconds is not None:
            mono = mono[: int(sr * self.max_seconds)]

        mono = mono - float(np.mean(mono))  # remove DC
        return sr, mono


# ----------------------------
# FFT (using numpy for speed) - removed custom fft_recursive
# ----------------------------

def next_power_of_two(n: int) -> int:
    """Return the smallest power of two greater than or equal to n."""
    p = 1
    while p < n:
        p <<= 1
    return p


def rfft_magnitude(x: np.ndarray, n_fft: int) -> np.ndarray:
    """
    Compute magnitude spectrum for non-negative frequencies only using numpy's FFT.
    """
    # np.fft.rfft is optimized for real input and handles zero-padding to n_fft
    spec = np.fft.rfft(x, n=n_fft)
    return np.abs(spec)


# ----------------------------
# Spectral feature extraction
# ----------------------------

class SpectralAnalyzer:
    """
    Computes:
    - PSD (Welch-style average periodogram)
    - Spectrogram statistics (STFT magnitude)
    """

    def __init__(self, n_fft: int = 2048, frame_len: int = 1024, hop_len: int = 512):
        self.n_fft = next_power_of_two(n_fft)
        self.frame_len = frame_len
        self.hop_len = hop_len

    @staticmethod
    def hamming(n: int) -> np.ndarray:
        """Hamming window (manual)."""
        idx = np.arange(n, dtype=np.float64)
        return 0.54 - 0.46 * np.cos(2.0 * np.pi * idx / (n - 1))

    def power_spectral_density(
        self,
        x: np.ndarray,
        sr: int,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Welch-style PSD:
        - Split signal into frames
        - Window each frame
        - Compute |FFT|^2
        - Average across frames
        """
        if len(x) < self.frame_len:
            x = np.pad(x, (0, self.frame_len - len(x)))

        win = self.hamming(self.frame_len)
        n_bins = self.n_fft // 2 + 1
        psd_acc = np.zeros(n_bins, dtype=np.float64)
        frames = 0

        for start in range(0, len(x) - self.frame_len + 1, self.hop_len):
            frame = x[start:start + self.frame_len] * win
            mag = rfft_magnitude(frame, self.n_fft)
            psd_acc += mag * mag
            frames += 1

        if frames > 0:
            psd = psd_acc / frames
        else:
            psd = psd_acc

        freqs = np.linspace(0.0, sr / 2.0, n_bins)
        return freqs, psd

    def spectrogram_magnitude(
        self,
        x: np.ndarray,
    ) -> np.ndarray:
        """
        STFT spectrogram magnitude:
        rows = time frames, cols = frequency bins
        """
        if len(x) < self.frame_len:
            x = np.pad(x, (0, self.frame_len - len(x)))

        win = self.hamming(self.frame_len)
        mags: List[np.ndarray] = []

        for start in range(0, len(x) - self.frame_len + 1, self.hop_len):
            frame = x[start:start + self.frame_len] * win
            mag = rfft_magnitude(frame, self.n_fft)
            mags.append(mag)

        if not mags:
            return np.zeros((0, self.n_fft // 2 + 1), dtype=np.float64)

        return np.vstack(mags)

    @staticmethod
    def summarize_psd(freqs: np.ndarray, psd: np.ndarray) -> Dict[str, float]:
        """
        Required PSD-based summary:
        - average power
        - min/max frequency (active band)
        - min/max power
        """
        if psd.size == 0:
            return {
                "avg_power": 0.0,
                "min_freq": 0.0,
                "max_freq": 0.0,
                "min_power": 0.0,
                "max_power": 0.0,
            }

        avg_power = float(np.mean(psd))
        min_power = float(np.min(psd))
        max_power = float(np.max(psd))

        # Define active region: bins above 1% of maximum power
        threshold = 0.01 * max_power if max_power > 0 else 0.0
        active = np.where(psd > threshold)[0]

        if active.size == 0:
            min_freq = 0.0
            max_freq = 0.0
        else:
            min_freq = float(freqs[active[0]])
            max_freq = float(freqs[active[-1]])

        return {
            "avg_power": avg_power,
            "min_freq": min_freq,
            "max_freq": max_freq,
            "min_power": min_power,
            "max_power": max_power,
        }

    @staticmethod
    def summarize_spectrogram(spec: np.ndarray) -> Dict[str, float]:
        """
        Spectrogram summary:
        - min/max magnitude
        - mean magnitude
        """
        if spec.size == 0:
            return {
                "spec_mean": 0.0,
                "spec_min_mag": 0.0,
                "spec_max_mag": 0.0,
            }

        return {
            "spec_mean": float(np.mean(spec)),
            "spec_min_mag": float(np.min(spec)),
            "spec_max_mag": float(np.max(spec)),
        }


# ----------------------------
# Aggregation
# ----------------------------

def aggregate_by_class(
    features: List[Dict[str, float]],
    labels: List[str],
) -> Dict[str, Dict[str, float]]:
    """Compute per-class average feature values."""
    grouped: Dict[str, List[Dict[str, float]]] = {}

    for feats, label in zip(features, labels):
        grouped.setdefault(label, []).append(feats)

    averages: Dict[str, Dict[str, float]] = {}
    for label, rows in grouped.items():
        averages[label] = {
            key: float(np.mean([r[key] for r in rows]))
            for key in rows[0].keys()
        }

    return averages


# ----------------------------
# Main routine
# ----------------------------

def main() -> None:
    dataset_zip_path = Path("/content/drive/MyDrive/train-bird-audio.zip")
    dataset_dir = Path("train-bird-audio")

    if not dataset_dir.exists() and dataset_zip_path.exists():
        print(f"Unzipping {dataset_zip_path}...")
        with zipfile.ZipFile(dataset_zip_path, "r") as zip_ref:
            zip_ref.extractall(".")
        print("Unzipping complete.")
    elif not dataset_dir.exists():
        raise FileNotFoundError(
            f"Neither {dataset_dir} nor {dataset_zip_path} found."
        )

    loader = FolderDatasetLoader(dataset_dir, extension="*.mp3")
    examples = loader.load()

    audio_loader = AudioLoader(max_seconds=5.0)
    analyzer = SpectralAnalyzer(n_fft=2048, frame_len=1024, hop_len=512)

    features: List[Dict[str, float]] = []
    labels: List[str] = []

    # No longer limiting processing, so the loop will run through all examples.
    print(f"Processing {len(examples)} audio examples...")
    processed_count = 0
    for ex in examples:
        # The `print` statement here is helpful to track progress during execution.
        print(f"  Processing {ex.path.name} (label: {ex.label})... (Processed {processed_count+1}/{len(examples)})")
        sr, signal = audio_loader.load_mono(ex.path)

        freqs, psd = analyzer.power_spectral_density(signal, sr)
        psd_feats = analyzer.summarize_psd(freqs, psd)

        spec = analyzer.spectrogram_magnitude(signal)
        spec_feats = analyzer.summarize_spectrogram(spec)

        combined = {}
        combined.update(psd_feats)
        combined.update(spec_feats)

        features.append(combined)
        labels.append(ex.label)
        processed_count += 1

    print(f"\nExtracted spectral features for {processed_count} audio examples.")

    per_class_avg = aggregate_by_class(features, labels)

    TARGET_SPECIES = ['aldfly', 'amecro', 'amered', 'brebla', 'purfin', 'pygnut']

    print("\nPer-class average spectral features (filtered for requested species):")
    for label in sorted(per_class_avg.keys()):
        if label in TARGET_SPECIES:
            avg = per_class_avg[label]
            # Formatted to match the user's requested output style
            print(
                f"{label:8s}\t"
                f"{avg['avg_power']:.4f}\t"
                f"{avg['min_freq']:.2f}\t"
                f"{avg['max_freq']:.2f}\t"
                f"{avg['min_power']:.1e}\t"
                f"{avg['max_power']:.2f}\t"
                f"{avg['spec_mean']:.4f}\t"
                f"{avg['spec_max_mag']:.2f}"
            )


if __name__ == "__main__":
    main()