# -*- coding: utf-8 -*-
"""Exercise 4 and 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZ_SEoJFRRcUh1SYCS7s1O8iUpm09ch6
"""

from pathlib import Path

file_path = Path('/content/drive/MyDrive/train-bird-audio.zip')

if file_path.exists():
    print(f"Het bestand '{file_path}' is gevonden in Google Drive.")
else:
    print(f"Het bestand '{file_path}' is NIET gevonden in Google Drive. Zorg ervoor dat het daar is geüpload.")

from google.colab import drive
drive.mount('/content/drive')

#!/usr/bin/env python3
"""
Task 5: Classification Model (fast + Colab-friendly)

This version is optimized for speed and reliability in Google Colab:
- No metadata.csv (labels inferred from folder names)
- Uses a small, fixed feature set (time + PSD summary + band energies)
- Avoids heavy STFT spectrogram matrices (expensive)
- Uses from-scratch FFT only (no numpy.fft)
- Processes at most N files per class (configurable) to keep runtime low
- Uses fixed random seed for replicability

Dependencies:
- numpy
- soundfile
- scikit-learn

Recommended Colab install:
!pip -q install soundfile scikit-learn
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple
import zipfile
import random

import numpy as np
import soundfile as sf
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    precision_recall_fscore_support,
)
from sklearn.model_selection import train_test_split


# ----------------------------
# Reproducibility
# ----------------------------

SEED = 42


def set_seed(seed: int) -> None:
    """Set seeds for reproducible results."""
    random.seed(seed)
    np.random.seed(seed)


# ----------------------------
# Data structures
# ----------------------------

@dataclass(frozen=True)
class AudioExample:
    """One audio sample with inferred class label."""
    path: Path
    label: str


# ----------------------------
# Dataset loading
# ----------------------------

class FolderDatasetLoader:
    """
    Loads audio files by scanning subdirectories.
    Each subdirectory name is treated as a class label.

    Speed control:
    - max_files_per_class limits number of files per label
    """

    def __init__(
        self,
        dataset_dir: Path,
        extension: str = "*.mp3",
        max_files_per_class: int = 80,
    ) -> None:
        self.dataset_dir = dataset_dir
        self.extension = extension
        self.max_files_per_class = max_files_per_class

    def load(self) -> List[AudioExample]:
        """Return a balanced list of examples (limited per class)."""
        if not self.dataset_dir.exists():
            raise FileNotFoundError("Dataset directory not found")

        examples: List[AudioExample] = []

        for class_dir in sorted(self.dataset_dir.iterdir()):
            if not class_dir.is_dir():
                continue

            label = class_dir.name
            files = sorted(class_dir.glob(self.extension))[: self.max_files_per_class]
            for audio_file in files:
                examples.append(AudioExample(path=audio_file, label=label))

        if not examples:
            raise RuntimeError("No audio files found in dataset")

        return examples


# ----------------------------
# Audio loading
# ----------------------------

class AudioLoader:
    """
    Loads audio into mono signals.

    Speed controls:
    - max_seconds truncates audio (e.g., 5 seconds)
    - downsample_to reduces sample rate by simple decimation (no resampling libs)
      Only safe if original sr is a multiple of downsample_to.
    """

    def __init__(
        self,
        max_seconds: float = 5.0,
        downsample_to: int = 16000,
    ) -> None:
        self.max_seconds = max_seconds
        self.downsample_to = downsample_to

    def load_mono(self, path: Path) -> Tuple[int, np.ndarray]:
        """Load audio file as mono float64 signal (optionally downsampled)."""
        data, sr = sf.read(str(path), dtype="float64", always_2d=True)
        mono = data.mean(axis=1)

        mono = mono[: int(sr * self.max_seconds)]
        mono = mono - float(np.mean(mono))  # remove DC

        mono, sr = self._downsample_if_possible(mono, sr)
        return sr, mono

    def _downsample_if_possible(self, x: np.ndarray, sr: int) -> Tuple[np.ndarray, int]:
        """Downsample by integer factor if possible (fast decimation)."""
        if sr <= self.downsample_to:
            return x, sr

        factor = sr // self.downsample_to
        if factor <= 1:
            return x, sr

        if sr % self.downsample_to != 0:
            # If not divisible, skip downsampling for correctness
            return x, sr

        return x[::factor], sr // factor


# ----------------------------
# FFT (from scratch, radix-2)
# ----------------------------

def next_power_of_two(n: int) -> int:
    """Return the smallest power of two >= n."""
    p = 1
    while p < n:
        p <<= 1
    return p


def fft_recursive(x: np.ndarray) -> np.ndarray:
    """Recursive radix-2 FFT. Input length must be a power of two."""
    n = len(x)
    if n == 1:
        return x

    even = fft_recursive(x[0::2])
    odd = fft_recursive(x[1::2])

    out = np.zeros(n, dtype=np.complex128)
    for k in range(n // 2):
        angle = -2.0 * np.pi * k / n
        w = complex(np.cos(angle), np.sin(angle))
        t = w * odd[k]
        out[k] = even[k] + t
        out[k + n // 2] = even[k] - t

    return out


def rfft_power(x: np.ndarray, n_fft: int) -> np.ndarray:
    """Return power spectrum for non-negative frequencies."""
    n_fft = next_power_of_two(n_fft)

    sig = np.zeros(n_fft, dtype=np.complex128)
    length = min(len(x), n_fft)
    sig[:length] = x[:length].astype(np.complex128)

    spec = fft_recursive(sig)
    half = n_fft // 2 + 1
    mag = np.abs(spec[:half])
    return mag * mag


# ----------------------------
# Fast spectral features (no STFT matrix)
# ----------------------------

class FastSpectralFeatures:
    """
    Computes fast frequency-domain features from a single windowed FFT.

    Features:
    - avg_power
    - min_power
    - max_power
    - min_freq / max_freq of active band (PSD > 1% max)
    - band powers: energy in fixed frequency bands (bird vocal ranges)
    """

    def __init__(self, n_fft: int = 2048) -> None:
        self.n_fft = next_power_of_two(n_fft)

    @staticmethod
    def hamming(n: int) -> np.ndarray:
        idx = np.arange(n, dtype=np.float64)
        return 0.54 - 0.46 * np.cos(2.0 * np.pi * idx / (n - 1))

    def extract(self, x: np.ndarray, sr: int) -> Dict[str, float]:
        if x.size == 0:
            return self._zeros()

        frame_len = min(len(x), self.n_fft)
        frame = x[:frame_len].copy()

        if frame_len < self.n_fft:
            frame = np.pad(frame, (0, self.n_fft - frame_len))

        frame *= self.hamming(self.n_fft)

        psd = rfft_power(frame, self.n_fft)
        freqs = np.linspace(0.0, sr / 2.0, len(psd))

        max_power = float(np.max(psd))
        threshold = 0.01 * max_power if max_power > 0 else 0.0
        active = np.where(psd > threshold)[0]

        if active.size == 0:
            min_freq = 0.0
            max_freq = 0.0
        else:
            min_freq = float(freqs[active[0]])
            max_freq = float(freqs[active[-1]])

        feats = {
            "avg_power": float(np.mean(psd)),
            "min_power": float(np.min(psd)),
            "max_power": max_power,
            "min_freq": min_freq,
            "max_freq": max_freq,
        }

        feats.update(self._band_powers(freqs, psd))
        return feats

    def _band_powers(self, freqs: np.ndarray, psd: np.ndarray) -> Dict[str, float]:
        """
        Band powers chosen to match typical bird vocalization regions.
        Adjust if your Task 3 results suggest different bands.
        """
        bands = [
            ("p_0_500", 0.0, 500.0),
            ("p_500_1500", 500.0, 1500.0),
            ("p_1500_3000", 1500.0, 3000.0),
            ("p_3000_6000", 3000.0, 6000.0),
            ("p_6000_10000", 6000.0, 10000.0),
        ]

        out: Dict[str, float] = {}
        for name, lo, hi in bands:
            idx = np.where((freqs >= lo) & (freqs < hi))[0]
            out[name] = float(np.mean(psd[idx])) if idx.size else 0.0
        return out

    @staticmethod
    def _zeros() -> Dict[str, float]:
        return {
            "avg_power": 0.0,
            "min_power": 0.0,
            "max_power": 0.0,
            "min_freq": 0.0,
            "max_freq": 0.0,
            "p_0_500": 0.0,
            "p_500_1500": 0.0,
            "p_1500_3000": 0.0,
            "p_3000_6000": 0.0,
            "p_6000_10000": 0.0,
        }


# ----------------------------
# Time-domain features (fast)
# ----------------------------

class TimeDomainFeatureExtractor:
    """Computes time-domain statistics (Task 2)."""

    @staticmethod
    def extract(x: np.ndarray) -> Dict[str, float]:
        if x.size == 0:
            return {
                "rms": 0.0,
                "std": 0.0,
                "crest": 0.0,
                "avg_amp": 0.0,
            }

        rms = float(np.sqrt(np.mean(x * x)))
        peak = float(np.max(np.abs(x)))
        crest = peak / rms if rms != 0.0 else 0.0

        return {
            "rms": rms,
            "std": float(np.std(x)),
            "crest": crest,
            "avg_amp": float(np.mean(np.abs(x))),
        }


class FeatureExtractor:
    """Combines time and fast frequency-domain features."""

    def __init__(self, spectral: FastSpectralFeatures) -> None:
        self.spectral = spectral

    def extract(self, x: np.ndarray, sr: int) -> Dict[str, float]:
        feats: Dict[str, float] = {}
        feats.update(TimeDomainFeatureExtractor.extract(x))
        feats.update(self.spectral.extract(x, sr))
        return feats


def dicts_to_matrix(rows: List[Dict[str, float]]) -> Tuple[np.ndarray, List[str]]:
    """Convert feature dicts to feature matrix X."""
    names = sorted(rows[0].keys())
    mat = np.array([[row[n] for n in names] for row in rows], dtype=np.float64)
    return mat, names


# ----------------------------
# Classification + evaluation
# ----------------------------

class BirdClassifier:
    """Random Forest classifier (fast + robust)."""

    def __init__(self, seed: int) -> None:
        self.model = RandomForestClassifier(
            n_estimators=250,
            random_state=seed,
            n_jobs=-1,
        )

    def fit(self, x_train: np.ndarray, y_train: List[str]) -> None:
        self.model.fit(x_train, y_train)

    def predict(self, x_test: np.ndarray) -> List[str]:
        return list(self.model.predict(x_test))


def print_metrics(y_true: List[str], y_pred: List[str]) -> None:
    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {prec:.4f} (macro)")
    print(f"Recall   : {rec:.4f} (macro)")
    print(f"F1-score : {f1:.4f} (macro)\n")

    print("Classification report:")
    print(classification_report(y_true, y_pred, zero_division=0))


# ----------------------------
# Main routine (Colab-friendly)
# ----------------------------

def main() -> None:
    set_seed(SEED)

    dataset_zip_path = Path("/content/drive/MyDrive/train-bird-audio.zip")
    dataset_dir = Path("train-bird-audio")

    if not dataset_dir.exists() and dataset_zip_path.exists():
        print(f"Unzipping {dataset_zip_path}...")
        with zipfile.ZipFile(dataset_zip_path, "r") as zip_ref:
            zip_ref.extractall(".")
        print("Unzipping complete.")
    elif not dataset_dir.exists():
        raise FileNotFoundError(
            f"Neither {dataset_dir} nor {dataset_zip_path} found."
        )

    # Speed: limit files per class and shorten audio
    loader = FolderDatasetLoader(
        dataset_dir=dataset_dir,
        extension="*.mp3",
        max_files_per_class=60,
    )
    examples = loader.load()

    audio_loader = AudioLoader(max_seconds=5.0, downsample_to=16000)
    spectral = FastSpectralFeatures(n_fft=2048)
    extractor = FeatureExtractor(spectral=spectral)

    feature_rows: List[Dict[str, float]] = []
    labels: List[str] = []

    for ex in examples:
        sr, x = audio_loader.load_mono(ex.path)
        feature_rows.append(extractor.extract(x, sr))
        labels.append(ex.label)

    x_mat, _ = dicts_to_matrix(feature_rows)

    x_train, x_test, y_train, y_test = train_test_split(
        x_mat,
        labels,
        test_size=0.2,
        random_state=SEED,
        stratify=labels if len(set(labels)) > 1 else None,
    )

    clf = BirdClassifier(seed=SEED)
    clf.fit(x_train, y_train)

    y_pred = clf.predict(x_test)
    print_metrics(y_test, y_pred)


if __name__ == "__main__":
    main()

#!/usr/bin/env python3
"""
Task 6: Explainability (model-specific)

This script extends the fast Task 5 classifier and adds explainability.
We use a *model-specific* explainability method for tree ensembles:

1) Built-in feature importance (Mean Decrease in Impurity) for RandomForest.
2) Permutation importance on the test set (model-agnostic but directly tied to the model).

Why this is suitable:
- RandomForest is a tree ensemble, so feature_importances_ is model-specific.
- Permutation importance quantifies performance drop when shuffling a feature.

No metadata.csv is used (labels inferred from folder names).
No numpy.fft is used (FFT from scratch).

Dependencies:
- numpy
- soundfile
- scikit-learn
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple
import zipfile
import random

import numpy as np
import soundfile as sf
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
from sklearn.metrics import (accuracy_score,
                             classification_report,
                             precision_recall_fscore_support)
from sklearn.model_selection import train_test_split


# ----------------------------
# Reproducibility
# ----------------------------

SEED = 42


def set_seed(seed: int) -> None:
    """Set seeds for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)


# ----------------------------
# Data structures
# ----------------------------

@dataclass(frozen=True)
class AudioExample:
    """One audio sample with inferred class label."""
    path: Path
    label: str


# ----------------------------
# Dataset loading
# ----------------------------

class FolderDatasetLoader:
    """
    Loads audio files by scanning subdirectories.
    Each subdirectory name is treated as a class label.
    """

    def __init__(
        self,
        dataset_dir: Path,
        extension: str = "*.mp3",
        max_files_per_class: int = 60,
    ) -> None:
        self.dataset_dir = dataset_dir
        self.extension = extension
        self.max_files_per_class = max_files_per_class

    def load(self) -> List[AudioExample]:
        if not self.dataset_dir.exists():
            raise FileNotFoundError("Dataset directory not found")

        examples: List[AudioExample] = []

        for class_dir in sorted(self.dataset_dir.iterdir()):
            if not class_dir.is_dir():
                continue

            label = class_dir.name
            files = sorted(class_dir.glob(self.extension))[:self.max_files_per_class]
            for audio_file in files:
                examples.append(AudioExample(path=audio_file, label=label))

        if not examples:
            raise RuntimeError("No audio files found in dataset")

        return examples


# ----------------------------
# Audio loading (fast)
# ----------------------------

class AudioLoader:
    """Loads audio into mono signals, with optional fast downsampling."""

    def __init__(self, max_seconds: float = 5.0, downsample_to: int = 16000) -> None:
        self.max_seconds = max_seconds
        self.downsample_to = downsample_to

    def load_mono(self, path: Path) -> Tuple[int, np.ndarray]:
        data, sr = sf.read(str(path), dtype="float64", always_2d=True)
        mono = data.mean(axis=1)

        mono = mono[: int(sr * self.max_seconds)]
        mono = mono - float(np.mean(mono))

        mono, sr = self._downsample_if_possible(mono, sr)
        return sr, mono

    def _downsample_if_possible(self, x: np.ndarray, sr: int) -> Tuple[np.ndarray, int]:
        if sr <= self.downsample_to:
            return x, sr

        factor = sr // self.downsample_to
        if factor <= 1:
            return x, sr

        if sr % self.downsample_to != 0:
            return x, sr

        return x[::factor], sr // factor


# ----------------------------
# FFT (from scratch)
# ----------------------------

def next_power_of_two(n: int) -> int:
    p = 1
    while p < n:
        p <<= 1
    return p


def fft_recursive(x: np.ndarray) -> np.ndarray:
    n = len(x)
    if n == 1:
        return x

    even = fft_recursive(x[0::2])
    odd = fft_recursive(x[1::2])

    out = np.zeros(n, dtype=np.complex128)
    for k in range(n // 2):
        angle = -2.0 * np.pi * k / n
        w = complex(np.cos(angle), np.sin(angle))
        t = w * odd[k]
        out[k] = even[k] + t
        out[k + n // 2] = even[k] - t

    return out


def rfft_power(x: np.ndarray, n_fft: int) -> np.ndarray:
    n_fft = next_power_of_two(n_fft)
    sig = np.zeros(n_fft, dtype=np.complex128)

    length = min(len(x), n_fft)
    sig[:length] = x[:length].astype(np.complex128)

    spec = fft_recursive(sig)
    half = n_fft // 2 + 1
    mag = np.abs(spec[:half])
    return mag * mag


# ----------------------------
# Features (fast)
# ----------------------------

class TimeDomainFeatureExtractor:
    """Time-domain features: RMS, STD, Crest factor, average amplitude."""

    @staticmethod
    def extract(x: np.ndarray) -> Dict[str, float]:
        if x.size == 0:
            return {"rms": 0.0, "std": 0.0, "crest": 0.0, "avg_amp": 0.0}

        rms = float(np.sqrt(np.mean(x * x)))
        peak = float(np.max(np.abs(x)))
        crest = peak / rms if rms != 0.0 else 0.0

        return {
            "rms": rms,
            "std": float(np.std(x)),
            "crest": crest,
            "avg_amp": float(np.mean(np.abs(x))),
        }


class FastSpectralFeatures:
    """
    Fast PSD summary + band powers from one windowed FFT.
    """

    def __init__(self, n_fft: int = 2048) -> None:
        self.n_fft = next_power_of_two(n_fft)

    @staticmethod
    def hamming(n: int) -> np.ndarray:
        idx = np.arange(n, dtype=np.float64)
        return 0.54 - 0.46 * np.cos(2.0 * np.pi * idx / (n - 1))

    def extract(self, x: np.ndarray, sr: int) -> Dict[str, float]:
        if x.size == 0:
            return self._zeros()

        frame_len = min(len(x), self.n_fft)
        frame = x[:frame_len].copy()

        if frame_len < self.n_fft:
            frame = np.pad(frame, (0, self.n_fft - frame_len))

        frame *= self.hamming(self.n_fft)

        psd = rfft_power(frame, self.n_fft)
        freqs = np.linspace(0.0, sr / 2.0, len(psd))

        max_power = float(np.max(psd))
        threshold = 0.01 * max_power if max_power > 0 else 0.0
        active = np.where(psd > threshold)[0]

        if active.size == 0:
            min_freq = 0.0
            max_freq = 0.0
        else:
            min_freq = float(freqs[active[0]])
            max_freq = float(freqs[active[-1]])

        feats = {
            "avg_power": float(np.mean(psd)),
            "min_power": float(np.min(psd)),
            "max_power": max_power,
            "min_freq": min_freq,
            "max_freq": max_freq,
        }
        feats.update(self._band_powers(freqs, psd))
        return feats

    def _band_powers(self, freqs: np.ndarray, psd: np.ndarray) -> Dict[str, float]:
        bands = [
            ("p_0_500", 0.0, 500.0),
            ("p_500_1500", 500.0, 1500.0),
            ("p_1500_3000", 1500.0, 3000.0),
            ("p_3000_6000", 3000.0, 6000.0),
            ("p_6000_10000", 6000.0, 10000.0),
        ]

        out: Dict[str, float] = {}
        for name, lo, hi in bands:
            idx = np.where((freqs >= lo) & (freqs < hi))[0]
            out[name] = float(np.mean(psd[idx])) if idx.size else 0.0
        return out

    @staticmethod
    def _zeros() -> Dict[str, float]:
        return {
            "avg_power": 0.0,
            "min_power": 0.0,
            "max_power": 0.0,
            "min_freq": 0.0,
            "max_freq": 0.0,
            "p_0_500": 0.0,
            "p_500_1500": 0.0,
            "p_1500_3000": 0.0,
            "p_3000_6000": 0.0,
            "p_6000_10000": 0.0,
        }


class FeatureExtractor:
    """Combines time and spectral features into one vector."""

    def __init__(self, spectral: FastSpectralFeatures) -> None:
        self.spectral = spectral

    def extract(self, x: np.ndarray, sr: int) -> Dict[str, float]:
        feats: Dict[str, float] = {}
        feats.update(TimeDomainFeatureExtractor.extract(x))
        feats.update(self.spectral.extract(x, sr))
        return feats


def dicts_to_matrix(rows: List[Dict[str, float]]) -> Tuple[np.ndarray, List[str]]:
    names = sorted(rows[0].keys())
    mat = np.array([[row[n] for n in names] for row in rows], dtype=np.float64)
    return mat, names


# ----------------------------
# Model + metrics
# ----------------------------

class BirdClassifier:
    """RandomForest classifier."""

    def __init__(self, seed: int) -> None:
        self.model = RandomForestClassifier(
            n_estimators=250,
            random_state=seed,
            n_jobs=-1,
        )

    def fit(self, x_train: np.ndarray, y_train: List[str]) -> None:
        self.model.fit(x_train, y_train)

    def predict(self, x_test: np.ndarray) -> List[str]:
        return list(self.model.predict(x_test))


def print_metrics(y_true: List[str], y_pred: List[str]) -> None:
    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {prec:.4f} (macro)")
    print(f"Recall   : {rec:.4f} (macro)")
    print(f"F1-score : {f1:.4f} (macro)\n")
    print("Classification report:")
    print(classification_report(y_true, y_pred, zero_division=0))


# ----------------------------
# Explainability
# ----------------------------

class ExplainabilityReporter:
    """
    Generates explainability outputs for a trained RandomForest model.

    Outputs:
    - Model-specific impurity-based importance (feature_importances_)
    - Permutation importance on test set
    """

    def __init__(self, feature_names: List[str]) -> None:
        self.feature_names = feature_names

    def report_model_importance(
        self,
        model: RandomForestClassifier,
        top_k: int = 12,
    ) -> None:
        """Print top-k model-specific feature importances."""
        importances = model.feature_importances_
        order = np.argsort(importances)[::-1]

        print("\nExplainability: model-specific feature importance (RandomForest)")
        for idx in order[:top_k]:
            name = self.feature_names[idx]
            score = float(importances[idx])
            print(f"- {name:16s} {score:.6f}")

    def report_permutation_importance(
        self,
        model: RandomForestClassifier,
        x_test: np.ndarray,
        y_test: List[str],
        seed: int,
        top_k: int = 12,
    ) -> None:
        """
        Permutation importance:
        Measures performance drop when shuffling a single feature.
        """
        result = permutation_importance(
            model,
            x_test,
            y_test,
            n_repeats=10,
            random_state=seed,
            n_jobs=-1,
        )

        importances = result.importances_mean
        order = np.argsort(importances)[::-1]

        print("\nExplainability: permutation importance (test set)")
        for idx in order[:top_k]:
            name = self.feature_names[idx]
            score = float(importances[idx])
            print(f"- {name:16s} {score:.6f}")


# ----------------------------
# Main routine
# ----------------------------

def main() -> None:
    set_seed(SEED)

    dataset_zip_path = Path("/content/train-bird-audio.zip")
    dataset_dir = Path("train-bird-audio")

    if not dataset_dir.exists() and dataset_zip_path.exists():
        print(f"Unzipping {dataset_zip_path}...")
        with zipfile.ZipFile(dataset_zip_path, "r") as zip_ref:
            zip_ref.extractall(".")
        print("Unzipping complete.")
    elif not dataset_dir.exists():
        raise FileNotFoundError(
            f"Neither {dataset_dir} nor {dataset_zip_path} found."
        )

    loader = FolderDatasetLoader(dataset_dir, extension="*.mp3", max_files_per_class=60)
    examples = loader.load()

    audio_loader = AudioLoader(max_seconds=5.0, downsample_to=16000)
    spectral = FastSpectralFeatures(n_fft=2048)
    extractor = FeatureExtractor(spectral=spectral)

    feature_rows: List[Dict[str, float]] = []
    labels: List[str] = []

    for ex in examples:
        sr, x = audio_loader.load_mono(ex.path)
        feature_rows.append(extractor.extract(x, sr))
        labels.append(ex.label)

    x_mat, feature_names = dicts_to_matrix(feature_rows)

    x_train, x_test, y_train, y_test = train_test_split(
        x_mat,
        labels,
        test_size=0.2,
        random_state=SEED,
        stratify=labels if len(set(labels)) > 1 else None,
    )

    clf = BirdClassifier(seed=SEED)
    clf.fit(x_train, y_train)

    y_pred = clf.predict(x_test)
    print_metrics(y_test, y_pred)

    reporter = ExplainabilityReporter(feature_names)
    reporter.report_model_importance(clf.model, top_k=12)
    reporter.report_permutation_importance(
        clf.model,
        x_test,
        y_test,
        seed=SEED,
        top_k=12,
    )


if __name__ == "__main__":
    main()