# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsDL9ebqLoTRyqQOuh_p_hKR06nu9G67
"""

#!/usr/bin/env python3
"""
Task 2: Data Exploration (time-domain statistics)

This script:
- Iterates over subdirectories (each = one bird species)
- Loads audio files directly from disk
- Computes time-domain statistics:
  * RMS
  * Standard deviation
  * Crest factor
  * Average amplitude
  * Min / Max amplitude
- Prints per-file results and per-class averages

"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple
import zipfile
import os

import numpy as np
import soundfile as sf


# ----------------------------
# Data structures
# ----------------------------

@dataclass(frozen=True)
class AudioExample:
    """One audio sample with inferred class label."""
    path: Path
    label: str


# ----------------------------
# Dataset loading
# ----------------------------

class FolderDatasetLoader:
    """
    Loads audio files by scanning subdirectories.
    Each subdirectory name is treated as a class label.
    """

    def __init__(self, dataset_dir: Path) -> None:
        self.dataset_dir = dataset_dir

    def load(self) -> List[AudioExample]:
        """Scan dataset directory and load audio paths."""
        if not self.dataset_dir.exists():
            raise FileNotFoundError("Dataset directory not found")

        examples: List[AudioExample] = []

        for class_dir in sorted(self.dataset_dir.iterdir()):
            if not class_dir.is_dir():
                continue

            label = class_dir.name
            # Changed from *.wav to *.mp3
            for audio_file in class_dir.glob("*.mp3"):
                examples.append(AudioExample(path=audio_file, label=label))

        if not examples:
            raise RuntimeError("No audio files found in dataset")

        return examples


# ----------------------------
# Audio loading
# ----------------------------

class AudioLoader:
    """Loads audio into mono signals."""

    def __init__(self, max_seconds: float | None = None) -> None:
        self.max_seconds = max_seconds

    def load_mono(self, path: Path) -> np.ndarray:
        """Load audio file as mono float64 signal."""
        data, sr = sf.read(str(path), dtype="float64", always_2d=True)
        mono = data.mean(axis=1)

        if self.max_seconds is not None:
            mono = mono[: int(sr * self.max_seconds)]

        mono = mono - float(np.mean(mono))  # remove DC
        return mono


# ----------------------------
# Feature extraction
# ----------------------------

class TimeDomainFeatureExtractor:
    """Computes time-domain statistics."""

    @staticmethod
    def rms(x: np.ndarray) -> float:
        return float(np.sqrt(np.mean(x * x))) if x.size else 0.0

    @staticmethod
    def standard_deviation(x: np.ndarray) -> float:
        return float(np.std(x)) if x.size else 0.0

    @staticmethod
    def crest_factor(x: np.ndarray) -> float:
        if x.size == 0:
            return 0.0
        peak = float(np.max(np.abs(x)))
        rms_val = TimeDomainFeatureExtractor.rms(x)
        return peak / rms_val if rms_val != 0.0 else 0.0

    @staticmethod
    def average_amplitude(x: np.ndarray) -> float:
        return float(np.mean(np.abs(x))) if x.size else 0.0

    @staticmethod
    def min_amplitude(x: np.ndarray) -> float:
        return float(np.min(x)) if x.size else 0.0

    @staticmethod
    def max_amplitude(x: np.ndarray) -> float:
        return float(np.max(x)) if x.size else 0.0

    def extract(self, x: np.ndarray) -> Dict[str, float]:
        return {
            "rms": self.rms(x),
            "std": self.standard_deviation(x),
            "crest": self.crest_factor(x),
            "avg_amp": self.average_amplitude(x),
            "min_amp": self.min_amplitude(x),
            "max_amp": self.max_amplitude(x),
        }


# ----------------------------
# Aggregation
# ----------------------------

def aggregate_by_class(
    features: List[Dict[str, float]],
    labels: List[str],
) -> Dict[str, Dict[str, float]]:
    """Compute per-class average features."""
    grouped: Dict[str, List[Dict[str, float]]] = {}

    for feats, label in zip(features, labels):
        grouped.setdefault(label, []).append(feats)

    averages: Dict[str, Dict[str, float]] = {}
    for label, rows in grouped.items():
        averages[label] = {
            key: float(np.mean([r[key] for r in rows]))
            for key in rows[0].keys()
        }

    return averages


# ----------------------------
# Main routine
# ----------------------------

def main() -> None:
    dataset_zip_path = Path("/content/train-bird-audio.zip")
    dataset_dir = Path("train-bird-audio")

    # Check if the dataset directory exists, if not, try to unzip
    if not dataset_dir.exists() and dataset_zip_path.exists():
        print(f"Unzipping {dataset_zip_path}...")
        with zipfile.ZipFile(dataset_zip_path, 'r') as zip_ref:
            zip_ref.extractall('.')
        print("Unzipping complete.")
    elif not dataset_dir.exists() and not dataset_zip_path.exists():
        raise FileNotFoundError(f"Neither {dataset_dir} nor {dataset_zip_path} found. Please ensure the dataset is available.")


    loader = FolderDatasetLoader(dataset_dir)
    examples = loader.load()

    audio_loader = AudioLoader(max_seconds=10.0)
    extractor = TimeDomainFeatureExtractor()

    features: List[Dict[str, float]] = []
    labels: List[str] = []

    for ex in examples:
        signal = audio_loader.load_mono(ex.path)
        feats = extractor.extract(signal)
        features.append(feats)
        labels.append(ex.label)

    print("First 10 extracted feature rows:")
    for ex, feats in list(zip(examples, features))[:10]:
        print(f"{ex.label:8s} {ex.path.name:25s} {feats}")

    per_class_avg = aggregate_by_class(features, labels)

    print("\nPer-class average time-domain features:")
    for label in sorted(per_class_avg.keys()):
        avg = per_class_avg[label]
        print(
            f"{label:8s} | "
            f"RMS={avg['rms']:.6f} "
            f"STD={avg['std']:.6f} "
            f"Crest={avg['crest']:.6f} "
            f"AvgAmp={avg['avg_amp']:.6f} "
            f"Min={avg['min_amp']:.6f} "
            f"Max={avg['max_amp']:.6f}"
        )


if __name__ == "__main__":
    main()

import shutil
from pathlib import Path

# Define paths
source_zip_path = Path("/content/drive/MyDrive/train-bird-audio.zip")
destination_zip_path = Path("/content/train-bird-audio.zip")

# Check if the source file exists in MyDrive
if source_zip_path.exists():
    print(f"Kopiëren van {source_zip_path} naar {destination_zip_path}...")
    shutil.copy(source_zip_path, destination_zip_path)
    print("Kopiëren voltooid.")
else:
    print(f"{source_zip_path} niet gevonden in Google Drive. Controleer het pad of upload het bestand.")
